version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: hackathon_news_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  sign_db:
    image: mysql:8.0
    container_name: sign_language_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${SIGN_DB_PASSWORD}
      MYSQL_DATABASE: ${SIGN_DB_NAME}
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      sign_db:
        condition: service_healthy
